const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

async function generateReceipt(payment, tenant, property) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument();
    const buffers = [];

    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => {
      const pdfData = Buffer.concat(buffers);
      resolve(pdfData);
    });
    doc.on('error', reject);

    // Header
    doc.fontSize(20).text('RentEase Payment Receipt', { align: 'center' });
    doc.moveDown();

    // Receipt details
    doc.fontSize(12);
    doc.text(`Receipt ID: ${payment.id}`);
    doc.text(`Transaction ID: ${payment.transactionId}`);
    doc.text(`Date: ${new Date(payment.paymentDate).toLocaleDateString()}`);
    doc.moveDown();

    // Tenant and Property info
    doc.text(`Tenant: ${tenant.user?.name}`);
    doc.text(`Email: ${tenant.user?.email}`);
    doc.text(`Property: ${property.address}`);
    doc.moveDown();

    // Payment details
    doc.text(`Amount Paid: $${payment.amount.toFixed(2)}`);
    doc.text(`Status: ${payment.status}`);
    doc.text(`Description: ${payment.description}`);
    doc.moveDown();

    // Footer
    doc.fontSize(10).text('Thank you for your payment!', { align: 'center' });
    doc.text('Generated by RentEase', { align: 'center' });

    doc.end();
  });
}

module.exports = { generateReceipt };